# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-thinking-stats" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "9c4f8361361607695a18426074058b80c8c858239f841f698b4672af10b438f4"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1a87cbd42502e551ba6168f89f853439749f007cdbc9b25de985af6afefc016"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c901b5fa00b8e31b0b3dc6a15b3c592f7ac50d5d02e5a3c66f932b95230ce0de"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eaae391fd5fd7ca214575ef1d6fc7bce6f68a734ae49858edf2299fe1b116bb1"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_linux_amd64.tar.gz"
    end
  end

  name "claude-thinking-stats"
  desc "Report how much of Claude Code's output was extended thinking, from local transcripts"
  homepage "https://github.com/nobu666/claude-thinking-stats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-thinking-stats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-thinking-stats"]
    end
  end

  # No zap stanza required
end
