# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-thinking-stats" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "0da63354f98fa811b5aaa70fbf482840042765a46ecb76083abaf8c67899ebe3"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3727e08ebbe1ce9b560bf6ae922680e9ef166008091186dcfa2f108523e5da1f"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0649696e7f347c2562dfff32cd7af7ae71df2576204ba38456a25f2ac32c8bbb"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f76b78af95b170101e4ec07f2857ef1e4f1c5ede4527252d7edde2b7739b9b8"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_linux_amd64.tar.gz"
    end
  end

  name "claude-thinking-stats"
  desc "Report how much of Claude Code's output was extended thinking, from local transcripts"
  homepage "https://github.com/nobu666/claude-thinking-stats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-thinking-stats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-thinking-stats"]
    end
  end

  # No zap stanza required
end
