# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-thinking-stats" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "adec4dee47a96bd91a34e1cf29598c646a59bf2aded884c64171cd740f95df34"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c34afb4ff6721a2f328389acf1f8c533a01a6764da1a1ef737f14c57593cd96"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac1090a2d0af5e450bd605862f5bdf5a3eefe4d49ad0299513168e552c09bb1d"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4eef513bd7f24c937840fd4439b9bd861b766efcfa82a232aecbc777f640f5b3"
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v#{version}/claude-thinking-stats_#{version}_linux_amd64.tar.gz"
    end
  end

  name "claude-thinking-stats"
  desc "Report how much of Claude Code's output was extended thinking, from local transcripts"
  homepage "https://github.com/nobu666/claude-thinking-stats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-thinking-stats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-thinking-stats"]
    end
  end

  # No zap stanza required
end
