# This file was generated by GoReleaser. DO NOT EDIT.
cask "localai-audit" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "19c53291b32d6835b117c3d7806067e094875ad835af06102734e0b925e64ad7"
      url "https://github.com/nobu666/localai-audit/releases/download/v#{version}/localai-audit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf7de46c1db3eba473f57b9036221dcc6f028d4f00339c5107dc5a280cc5817c"
      url "https://github.com/nobu666/localai-audit/releases/download/v#{version}/localai-audit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "394c92662d9ab9fff481a4d066dac4ca1584a983f7fce7709c615a3ea43c71ca"
      url "https://github.com/nobu666/localai-audit/releases/download/v#{version}/localai-audit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4cff2210371b80ce00029dc0f1c6ba74d46fc2ce3ff93401181ff8cc5ad0432"
      url "https://github.com/nobu666/localai-audit/releases/download/v#{version}/localai-audit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "localai-audit"
  desc "Audit local AI services for all-interface binding and DNS-rebinding exposure"
  homepage "https://github.com/nobu666/localai-audit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localai-audit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/localai-audit"]
    end
  end

  # No zap stanza required
end
