# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-exposure" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "52468df57ced16f5c1b434d2e1a3b8582e42ca93c5599a356504d2fca1a625e2"
      url "https://github.com/nobu666/mcp-exposure/releases/download/v#{version}/mcp-exposure_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf69409291d2fda3b03acc8e0c260ef629a067c1930e325ed0f65035b3fada9c"
      url "https://github.com/nobu666/mcp-exposure/releases/download/v#{version}/mcp-exposure_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b6387907826b0f7b973264a8d887fb09473e7b990ed8659ccdd4e7aad8f2ee45"
      url "https://github.com/nobu666/mcp-exposure/releases/download/v#{version}/mcp-exposure_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b66a40b76c3c4443029f7919b25e2476921b2cd9f5ecc6093ae63ecccf760619"
      url "https://github.com/nobu666/mcp-exposure/releases/download/v#{version}/mcp-exposure_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcp-exposure"
  desc "List the MCP servers registered on this machine and how each one is exposed"
  homepage "https://github.com/nobu666/mcp-exposure"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-exposure"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-exposure"]
    end
  end

  # No zap stanza required
end
