# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeThinkingStats < Formula
  desc "Report how much of Claude Code's output was extended thinking, from local transcripts"
  homepage "https://github.com/nobu666/claude-thinking-stats"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v0.1.0/claude-thinking-stats_0.1.0_darwin_amd64.tar.gz"
      sha256 "02b2ccff2180a7868da49913c64a2bf97e3a1d1215d69a6cdb2baea90ac9236a"

      define_method(:install) do
        bin.install "claude-thinking-stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v0.1.0/claude-thinking-stats_0.1.0_darwin_arm64.tar.gz"
      sha256 "876463c44268972e1d6f2f402ee170ec8a2d1d612c882a81c1020a5493b90605"

      define_method(:install) do
        bin.install "claude-thinking-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v0.1.0/claude-thinking-stats_0.1.0_linux_amd64.tar.gz"
      sha256 "f309b2159e22f74a29efd7fe3b7a3771a8415d6389c24f4888426dfa9268b828"
      define_method(:install) do
        bin.install "claude-thinking-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/claude-thinking-stats/releases/download/v0.1.0/claude-thinking-stats_0.1.0_linux_arm64.tar.gz"
      sha256 "1ac7d56c3cad0d079f2619871d61b94d11a92af4cc26a7b41a2aa93fcca3ced3"
      define_method(:install) do
        bin.install "claude-thinking-stats"
      end
    end
  end

  test do
    system "#{bin}/claude-thinking-stats", "--help"
  end
end
