# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalaiAudit < Formula
  desc "Audit local AI services for all-interface binding and DNS-rebinding exposure"
  homepage "https://github.com/nobu666/localai-audit"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.1/localai-audit_0.3.1_darwin_amd64.tar.gz"
      sha256 "b6fbf3ee472e104891f19df17cc6fc657e0b55654539c2e89a32eaed74bf161d"

      define_method(:install) do
        bin.install "localai-audit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.1/localai-audit_0.3.1_darwin_arm64.tar.gz"
      sha256 "9186d12c77e41eeed44bdfb68c829ad2598b6c2ef4d67453ee62f3a633fbd1f0"

      define_method(:install) do
        bin.install "localai-audit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.1/localai-audit_0.3.1_linux_amd64.tar.gz"
      sha256 "465b61255f687cd7829bf026e5f5212889e1159577f405931940884dd0b65e43"
      define_method(:install) do
        bin.install "localai-audit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.1/localai-audit_0.3.1_linux_arm64.tar.gz"
      sha256 "5eb252ef9e2af9e8bd408ddd59e97bfb6c99246f6556f0479d0a8bc262e0a9ba"
      define_method(:install) do
        bin.install "localai-audit"
      end
    end
  end

  test do
    system "#{bin}/localai-audit", "--help"
  end
end
