# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalaiAudit < Formula
  desc "Audit local AI services for all-interface binding and DNS-rebinding exposure"
  homepage "https://github.com/nobu666/localai-audit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.0/localai-audit_0.3.0_darwin_amd64.tar.gz"
      sha256 "d7e0041e4220250ca229316da536cf7464fe259769fc293b8e175b4cff7796af"

      define_method(:install) do
        bin.install "localai-audit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.0/localai-audit_0.3.0_darwin_arm64.tar.gz"
      sha256 "666b226009869de615d09d46c46c90b8cf309b960e6b8458222377c767a1c54c"

      define_method(:install) do
        bin.install "localai-audit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.0/localai-audit_0.3.0_linux_amd64.tar.gz"
      sha256 "f3063ea2383a4b7c059fbd7ed513dc83ae6b8d2089f30a6e0f1f792e835c01ba"
      define_method(:install) do
        bin.install "localai-audit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.3.0/localai-audit_0.3.0_linux_arm64.tar.gz"
      sha256 "f3bdc41c560dccb2df407df52f86fe59ab48c43823ea00a915ad83e5817e4360"
      define_method(:install) do
        bin.install "localai-audit"
      end
    end
  end

  test do
    system "#{bin}/localai-audit", "--help"
  end
end
