# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalaiAudit < Formula
  desc "Audit local AI services for all-interface binding and DNS-rebinding exposure"
  homepage "https://github.com/nobu666/localai-audit"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.2.1/localai-audit_0.2.1_darwin_amd64.tar.gz"
      sha256 "2f7fd6f27922ab46d88ed006d9ac01117ae8f71a7c51b473c31e0e7fcd7bd3a7"

      define_method(:install) do
        bin.install "localai-audit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.2.1/localai-audit_0.2.1_darwin_arm64.tar.gz"
      sha256 "f25c2533d4956187e2803d54d7e225c7efc6ca955226986ac76a2f31a7202fb6"

      define_method(:install) do
        bin.install "localai-audit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.2.1/localai-audit_0.2.1_linux_amd64.tar.gz"
      sha256 "3c642a31c1f7981319c0cdc83a1c8facd93f05d98c9ba1cd9705690664ba3558"
      define_method(:install) do
        bin.install "localai-audit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/localai-audit/releases/download/v0.2.1/localai-audit_0.2.1_linux_arm64.tar.gz"
      sha256 "1caccbc28b3219dcd266fc9a13bc4d6401bde16d97052938303f718711e2010b"
      define_method(:install) do
        bin.install "localai-audit"
      end
    end
  end

  test do
    system "#{bin}/localai-audit", "--help"
  end
end
