# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpExposure < Formula
  desc "List the MCP servers registered on this machine and how each one is exposed"
  homepage "https://github.com/nobu666/mcp-exposure"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nobu666/mcp-exposure/releases/download/v0.2.1/mcp-exposure_0.2.1_darwin_amd64.tar.gz"
      sha256 "8ba042e19c750ff3c34da061644f25c0295fb6f72d869a0c4301f5c95e83fb4e"

      define_method(:install) do
        bin.install "mcp-exposure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nobu666/mcp-exposure/releases/download/v0.2.1/mcp-exposure_0.2.1_darwin_arm64.tar.gz"
      sha256 "d5f52179ba31cd4673738e3564625e982aa21d6323e1051a0582099c08c20913"

      define_method(:install) do
        bin.install "mcp-exposure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/mcp-exposure/releases/download/v0.2.1/mcp-exposure_0.2.1_linux_amd64.tar.gz"
      sha256 "6ac9f8669feefb5d74d76a9fd97a4fb9aeda081e06281d2fe45cc31953cedde4"
      define_method(:install) do
        bin.install "mcp-exposure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nobu666/mcp-exposure/releases/download/v0.2.1/mcp-exposure_0.2.1_linux_arm64.tar.gz"
      sha256 "88cc4e792957b71fb00181f2a857234223e4c790a405fd27666f70e62f62c51d"
      define_method(:install) do
        bin.install "mcp-exposure"
      end
    end
  end

  test do
    system "#{bin}/mcp-exposure", "--help"
  end
end
